version: '3.3'
services:
  docs:
    image: swaggerapi/swagger-editor
    restart: always
    environment:
      URL: /api
    ports:
      - 80:8080
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
